author = "replica42"
baseURL = "https://replica-42.github.io"
defaultContentLanguage = "cn"
languageCode = "zh-CN"
title = "幻想图书馆"
copyright = "replica42"
hasCJKLanguage = true
enableRobotsTXT = true
disqusShortname = "replica-42-github-io"


[markup]
[markup.highlight]
style = "monokailight"

[permalinks]
posts = "/:year/:month/:filename/"

[params]
description = "雖然不知道爲什麽，不過似乎任何人都拼命想對某個人或對這個世界傾訴一些事情。"
favicon = "favicon.ico"
useChineseFonts = true
math = true

[[menu.main]]
url = "/posts/"
name = "归档"
weight = 1

[[menu.main]]
url = "/categories/"
name = "分类"
weight = 2

[module]
[[module.imports]]
path = 'github.com/heyeshuang/hugo-theme-tokiwa'

[social]
github = "https://github.com/replica-42"
mail = "mailto:replica42@outlook.com"
twitter = "https://twitter.com/replica_42"
weibo = "https://weibo.com/u/5114219480"